[package]
name = "view"
version = "0.1.0"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "a macro for constructing views"
repository = "https://github.com/richardanaya/view/"

[lib]
proc-macro = true